#!/bin/sh
. /lib/functions.sh

IP="/usr/sbin/ip -4"

help()
{
	cat <<EOF
Syntax: direc-route [command]

Available commands:
	flush         Unload directional rules
	reset         Reload directional rules
EOF
}

flush() {
	rule_existed=`$IP rule list |grep rt_ | awk '{print $3 " table " $5}'|wc -l`
	if [ $rule_existed -ne 0 ];then
		$IP rule list |grep rt_ | awk '{print $3 " table " $5}' > /tmp/iplist_dir_routing
		cat /tmp/iplist_dir_routing | while read myip
		do
			$IP rule del from $myip
		done
		rm /tmp/iplist_dir_routing
	fi
}

set_direc_route_rules() {
        local device                        
                                                                                           
        config_load mwan3                                                                  
                                       
        device=$(uci get -p /var/state network.$1.ifname) &> /dev/null                     
                                                                                           
        if [ -n "$device" ] ; then                    
		/usr/sbin/wanruleadd_directional_route $1 $device ifup
        fi                                                            
}

reset() {
	flush
        config_load mwan3
        config_foreach set_direc_route_rules interface
}

del() {
	if [ -n "$1" ] ; then
		/usr/sbin/wanruleadd_directional_route $1 ifdown
	fi
}

case "$1" in
	flush|reset)
                $*                                                 
        ;;
	del)
		$* $2
	;;
        *)                                                           
                help                                                
        ;;                                                            
esac                                          
                                            
exit 0       
