#!/bin/sh
	[ -x /usr/sbin/ip ] || exit 1
	touch /tmp/kill_wanruleadd
	sleep 1
	[ -f /tmp/kill_wanruleadd ] && rm /tmp/kill_wanruleadd
	rule_existed=`ip rule list |grep rt_ | awk '{print $5 " table " $7}'|wc -l`          
	if [ $rule_existed -ne 0 ];then
		ip rule list |grep rt_ | awk '{print $5 " table " $7}' > /tmp/iplist_all
		cat /tmp/iplist_all | while read myip
		do                                     
			ip rule del to $myip
		done
		rm /tmp/iplist_all
	fi
