#!/bin/sh
#
# Copyright (C) 2011 OpenWrt.org
#

[ ! -e /etc/config/network ] && exit 0


. /lib/functions/uci-defaults.sh
local wan_mac
local lan_mac
local lan_ifname
wan_mac=$(cat /sys/class/net/eth0/address)
eth1_mac=$(cat /sys/class/net/eth1/address)
eth2_mac=$(cat /sys/class/net/eth2/address)
eth3_mac=$(cat /sys/class/net/eth3/address)
eth4_mac=$(cat /sys/class/net/eth4/address)
eth5_mac=$(cat /sys/class/net/eth5/address)
if [ -n "$eth5_mac" ];then
	lan_ifname="eth1 eth2 eth3 eth4 eth5"
	lan_mac=$eth5_mac
elif [ -n "$eth4_mac" ];then
	lan_ifname="eth1 eth2 eth3 eth4"
	lan_mac=$eth4_mac
elif [ -n "$eth3_mac" ];then
	lan_ifname="eth1 eth2 eth3"
	lan_mac=$eth3_mac
elif [ -n "$eth2_mac" ];then
	lan_ifname="eth1 eth2"
	lan_mac=$eth2_mac
elif [ -n "$eth1_mac" ];then
	lan_ifname="eth1"
	lan_mac=$eth1_mac
fi

def_str=`uci get network.def 2>/dev/null`
[ -z "$def_str" ] &&
uci batch <<EOF
set network.def=def
set network.def.def_lan='$lan_ifname'
set network.def_wan='eth0'
set network.def_lan_macaddr='$lan_mac'
set network.def_wan_macaddr='$wan_mac'
set network.wan.macaddr='$wan_mac'
set network.lan.macaddr='$lan_mac'
set network.lan.ifname='$lan_ifname'
EOF

uci commit network
exit 0
