#!/bin/sh
	device=`basename $DEVPATH`

	case "$ACTION" in
		add)
			for i in $(echo $device | grep 'sd[a-z][0-9]')
			do
				exist_debugfs=`/bin/mount |grep debugfs`
				exist_jffs2=`/bin/mount |grep jffs2`
				if [ x"$exist_debugfs" = "x" -o x"$exist_jffs2" = "x" ];then
					/bin/mount_disk $i &
					break
				fi
				mkdir -p /mnt/$i
				mount -t vfat -o iocharset=utf8,rw /dev/$i /mnt/$i
				if [ "$?" -ne 0 ];then
					mount -o rw /dev/$i /mnt/$i
				fi
				if [ ! -d "/www-comfast/data/temp" ]; then
					mkdir /www-comfast/data/temp
				fi
				df -h |grep /dev/sd > /www-comfast/data/temp/udisk_info.txt
				blkid |grep /dev/sd >> /www-comfast/data/temp/udisk_info.txt
				
				php_start=`pidof php-fpm`
				if [ x"$php_start" = "x" ];then
				        uci set php5-fpm.@php5-fpm[0].enabled=1
				        uci commit php5-fpm
				        /etc/init.d/php5-fpm restart
				fi
				break
			done

			for i in $(echo $device | grep 'mmcblk[0-9]p[0-9]')
			do
				mkdir -p /mnt/$i
				mount -t vfat -o iocharset=utf8,rw /dev/$i /mnt/$i
				if [ "$?" -ne 0 ];then
					mount -o rw /dev/$i /mnt/$i
				fi
				break
			done
			;;
		remove)
			UMOUNT=$(echo $device | grep 'mmcblk[0-9]p[0-9]')
			if [ "$UMOUNT" = "" ]; then
				UMOUNT=$(echo $device | grep 'sd[a-z][0-9]')
			fi
			if [ "$UMOUNT" = "" ]; then
				break
			fi			
			FOUND=$(mount | grep -o /mnt/$UMOUNT)
			umount $FOUND
			rm $FOUND -fr

			if [ ! -d "/www-comfast/data/temp" ]; then
				mkdir /www-comfast/data/temp
			fi
			df -h |grep /dev/sd > /www-comfast/data/temp/udisk_info.txt
			blkid |grep /dev/sd >> /www-comfast/data/temp/udisk_info.txt

			exist_udisk=`/bin/mount |grep /mnt/'sd[a-z][0-9]'`
			if [ x"$exist_udisk" = "x" ];then
				php_start=`uci get php5-fpm.@php5-fpm[0].enabled 2>/dev/null`
				if [ $php_start -eq 1 ];then
					uci set php5-fpm.@php5-fpm[0].enabled=0
					uci commit php5-fpm
					/etc/init.d/php5-fpm stop
				fi
			fi
			;;
	esac
