#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99

start() {
	board_name=`cat /tmp/sysinfo/board_name`
	case $board_name in
		cf-e356a |\
		cf-wa750)
			echo "pci check:cf-e356/cf-wa750" > /dev/console	
		;;
		*)
			exit 0
		;;
	esac
	pcie_status=`dmesg | grep "PCIe link is down"`		
	[ -n "$pcie_status" ] && {
		reboot 
	}
}

stop() {
	killall pcie_down_reboot 
}
