#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2011 OpenWrt.org
# Copyright (C) 2011 Artem Makhutov
# Copyright (C) 2014 Noah Meyerhans <frodo@morgul.net>

USE_PROCD=1

START=49

start_service() {
    mkdir -m 0700 -p /var/racoon
    if [ -f /etc/ipsec.conf ];then
	/usr/sbin/setkey -f /etc/ipsec.conf
    else
	exit 0
    fi
    procd_open_instance
    procd_set_param command /usr/sbin/racoon -F -f /etc/racoon.conf
    procd_set_param respawn
    procd_close_instance
}
