#!/bin/sh /etc/rc.common

START=97
STOP=98

USE_PROCD=1

start_service() {
	radius_enable=`uci get wifilith.radius.enable 2>/dev/null`
	if [ a"$radius_enable" == "a1" ]; then
		procd_open_instance
		procd_set_param command /usr/bin/radius_h_b
		procd_set_param respawn
		procd_close_instance
	fi
}

stop_service() {
	killall radius_h_b
}

restart() {
	sleep 1
	trap '' TERM
	stop "$@"
	start "$@"
}