#!/bin/sh /etc/rc.common
START=99

start()
{
	if [ -f /etc/crontabs/root ];then
		cmd=`cat /etc/crontabs/root | grep drop_caches`
		if [ -z "$cmd" ];then
			echo "* * * * * sync; echo 3 > /proc/sys/vm/drop_caches" >> /etc/crontabs/root

		cmd=`cat /etc/crontabs/root | grep loadrrd`
		if [ -n "$cmd" ];then
			/etc/init.d/cron restart
			exit 0
		fi
	fi
	echo "*/1 * * * * /etc/rrd/loadrrd start" >> /etc/crontabs/root
	/etc/init.d/cron restart
}
