#!/bin/sh /etc/rc.common
START=99

start()
{
	if [ -f /etc/crontabs/root ];then
		cmd=`cat /etc/crontabs/root | grep drop_caches`
		if [ -z "$cmd" ];then
			echo "* * * * * sync; echo 3 > /proc/sys/vm/drop_caches" >> /etc/crontabs/root

		cmd=`cat /etc/crontabs/root | grep loadrrd`
		if [ -n "$cmd" ];then
			sed -i "/loadrrd/d" "/etc/crontabs/root"
		fi
	fi
	/etc/init.d/cron restart
}
