#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99

start() {
	[ -f /lib/modules/usb-common.ko ] && insmod /lib/modules/usb-common.ko
	[ -f /lib/modules/usbcore.ko ] && insmod /lib/modules/usbcore.ko
	[ -f /lib/modules/usb-storage.ko ] && insmod /lib/modules/usb-storage.ko
	[ -f /lib/modules/ehci-hcd.ko ] && insmod /lib/modules/ehci-hcd.ko
	[ -f /lib/modules/ehci-platform.ko ] && insmod /lib/modules/ehci-platform.ko
}

stop() {
	[ -f /lib/modules/ehci-platform.ko ] && rmmod ehci-platform.ko
	[ -f /lib/modules/ehci-hcd.ko ] && rmmod ehci-hcd.ko
	[ -f /lib/modules/usb-storage.ko ] && rmmod usb-storage.ko
	[ -f /lib/modules/usbcore.ko ] && rmmod usbcore.ko
	[ -f /lib/modules/usb-common.ko ] && rmmod usb-common.ko
}
