#!/bin/sh /etc/rc.common

START=51
STOP=52

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/webmgnt
	procd_set_param respawn
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger "webmgnt"
}
