#!/bin/sh /etc/rc.common

START=97
STOP=98

USE_PROCD=1

start_service() {
	ac_control_enable=`uci get system.ac_control.ac_enable`
	ac_identify=`uci get system.ac_control.ac_identify`
	if [ "$ac_identify" == "1" -a "$ac_control_enable" == "0" ]; then
		exit
	fi
	procd_open_instance
	procd_set_param command /usr/bin/wtpd -f
	procd_set_param respawn
	procd_close_instance

	[ -e "/usr/bin/wtpd_ubus" ] && {
		procd_open_instance
		procd_set_param command /usr/bin/wtpd_ubus
		procd_set_param respawn
		procd_close_instance
	}

	procd_open_instance
	procd_set_param command /usr/bin/wtpd_udp
	procd_set_param respawn
	procd_close_instance

	[ -e "/usr/bin/wtpd_server" ] && {
		procd_open_instance
		procd_set_param command /usr/bin/wtpd_server
		procd_set_param respawn
		procd_close_instance
	}
}

reload_service() {
	killall wtpd
	killall wtpd_udp
	[ -e "/usr/bin/wtpd_ubus" ] && killall wtpd_ubus
	[ -e "/usr/bin/wtpd_server" ] && killall wtpd_server
}

stop_service() {
	killall wtpd
	killall wtpd_udp
	[ -e "/usr/bin/wtpd_ubus" ] && killall wtpd_ubus
	[ -e "/usr/bin/wtpd_server" ] && killall wtpd_server
}

service_running() {
	sleep 1
}

service_triggers()
{
	procd_add_reload_trigger "wtpd"
}

restart() {
	sleep 1
	trap '' TERM
	stop "$@"
	start "$@"
}

shutdown() {
	stop
}
