#!/bin/sh

local workmode=`uci get network.workmode 2>/dev/null`
[ -n "$workmode" ] && [ "$workmode" = "ap" -o ${workmode:0:3} = "wds" ] && {
	fw3 flush
	exit 0
}

[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0
[ "$ACTION" = ifupdate -a -z "$IFUPDATE_ADDRESSES" -a -z "$IFUPDATE_DATA" ] && exit 0

/etc/init.d/firewall enabled || exit 0

if [ "$INTERFACE" == "pptp" ] || [ "$INTERFACE" == "l2tp" ];then
	/etc/fw3_reload
	exit 0
fi
fw3 -q network "$INTERFACE" >/dev/null || exit 0

logger -t firewall "Reloading firewall due to $ACTION of $INTERFACE ($DEVICE)"
/etc/fw3_reload
