#!/bin/sh

if [ $# -ne 2 ];then
	exit 0
fi
		rrdfile=/tmp/rrd/$1.rrd
		PIC=/tmp/rrd/$1_hour.png
		time=28800
		iface_name=$2
		
# only run, if no other rrdtool is running
        if [ -n "$(ps | grep rrdtool | grep -v grep)" ];then
                return
        fi

	rrdfile=/tmp/rrd/$1.rrd
	time=28800
	PIC=/tmp/rrd/$1_hour.dump
	rrdtool fetch "${rrdfile}" AVERAGE -s -"${time}" -r 900 > "${PIC}"

	
        
				
	rrdfile=/tmp/rrd/$1.rrd
	time=86400
	PIC=/tmp/rrd/$1_day.dump
	rrdtool fetch "${rrdfile}" AVERAGE -s -"${time}" -r 900 > "${PIC}"

	
	rrdfile=/tmp/rrd/$1.rrd
	time=604800
	PIC=/tmp/rrd/$1_week.dump
	rrdtool fetch "${rrdfile}" AVERAGE -s -"${time}" -r 900 > "${PIC}"
	
	rrdfile=/tmp/rrd/$1.rrd
	PIC=/tmp/rrd/$1_hour.png
	time=28800
	iface_name=$2

	  rrdtool graph "${PIC}" -a PNG -s -"${time}" -w 550 -h 240 -v "bytes/s" \
                'DEF:in='${rrdfile}':rx_bytes:AVERAGE' \
                'DEF:out='${rrdfile}':tx_bytes:AVERAGE' \
                'CDEF:out_neg=out,-1,*' \
                'AREA:in#32CD32:rx_bytes' \
                'LINE1:in#336600' \
                GPRINT:in:"MAX:  Max\\: %5.1lf %s" \
                GPRINT:in:"AVERAGE: Avg\\: %5.1lf %S" \
                GPRINT:in:"LAST: Current\\: %5.1lf %Sbytes/sec\\n" \
                'AREA:out_neg#4169E1:tx_bytes' \
                'LINE1:out_neg#0033CC' \
                GPRINT:out:"MAX:  Max\\: %5.1lf %S" \
                GPRINT:out:"AVERAGE: Avg\\: %5.1lf %S" \
                GPRINT:out:"LAST: Current\\: %5.1lf %Sbytes/sec" \
                'HRULE:0#000000' -t "${iface_name} traffic - 8 hours - 1 minute average"
				
		time=86400
		PIC=/tmp/rrd/$1_day.png
		rrdtool graph "${PIC}" -a PNG -s -"${time}" -w 550 -h 240 -v "bytes/s" \
                'DEF:in='${rrdfile}':rx_bytes:AVERAGE' \
                'DEF:out='${rrdfile}':tx_bytes:AVERAGE' \
                'CDEF:out_neg=out,-1,*' \
                'AREA:in#32CD32:rx_bytes' \
                'LINE1:in#336600' \
                GPRINT:in:"MAX:  Max\\: %5.1lf %s" \
                GPRINT:in:"AVERAGE: Avg\\: %5.1lf %S" \
                GPRINT:in:"LAST: Current\\: %5.1lf %Sbytes/sec\\n" \
                'AREA:out_neg#4169E1:tx_bytes' \
                'LINE1:out_neg#0033CC' \
                GPRINT:out:"MAX:  Max\\: %5.1lf %S" \
                GPRINT:out:"AVERAGE: Avg\\: %5.1lf %S" \
                GPRINT:out:"LAST: Current\\: %5.1lf %Sbytes/sec" \
                'HRULE:0#000000' -t "${iface_name} traffic - 1 day - 1 minute average"
				
		time=604800
		PIC=/tmp/rrd/$1_week.png
		rrdtool graph "${PIC}" -a PNG -s -"${time}" -w 550 -h 240 -v "bytes/s" \
                'DEF:in='${rrdfile}':rx_bytes:AVERAGE' \
                'DEF:out='${rrdfile}':tx_bytes:AVERAGE' \
                'CDEF:out_neg=out,-1,*' \
                'AREA:in#32CD32:rx_bytes' \
                'LINE1:in#336600' \
                GPRINT:in:"MAX:  Max\\: %5.1lf %s" \
                GPRINT:in:"AVERAGE: Avg\\: %5.1lf %S" \
                GPRINT:in:"LAST: Current\\: %5.1lf %Sbytes/sec\\n" \
                'AREA:out_neg#4169E1:tx_bytes' \
                'LINE1:out_neg#0033CC' \
                GPRINT:out:"MAX:  Max\\: %5.1lf %S" \
                GPRINT:out:"AVERAGE: Avg\\: %5.1lf %S" \
                GPRINT:out:"LAST: Current\\: %5.1lf %Sbytes/sec" \
                'HRULE:0#000000' -t "${iface_name} traffic - 1 week - 1 minute average"
				
