#!/bin/sh
rrdfile=/tmp/rrd/cpu.rrd
#PIC=/tmp/rrd/cpu.png


# only run, if no other rrdtool is running
        if [ -n "$(ps | grep rrdtool | grep -v grep)" ] ; then
                return
        fi

	time=28800
	PIC=/tmp/rrd/cpu_hour.dump
	rrdtool fetch "${rrdfile}" AVERAGE -s -"${time}" -r 900 > "${PIC}"

       		

	time=86400
	PIC=/tmp/rrd/cpu_day.dump
	rrdtool fetch "${rrdfile}" AVERAGE -s -"${time}" -r 900 > "${PIC}"
			
	
	time=604800
	PIC=/tmp/rrd/cpu_week.dump
	rrdtool fetch "${rrdfile}" AVERAGE -s -"${time}" -r 900 > "${PIC}"



