#!/bin/sh
# Copyright (C) 2006-2010 OpenWrt.org

export HOTPLUG_TYPE="$1"

. /lib/functions.sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin
LOGNAME=root
USER=root
export PATH LOGNAME USER
export DEVICENAME="${DEVPATH##*/}"

[ \! -z "$1" -a -d /etc/hotplug.d/$1 ] && {
	if [ -n "$2" ]; then
		[ -f /etc/hotplug.d/iface/$2 ] && . /etc/hotplug.d/iface/$2
	else
		for script in $(ls /etc/hotplug.d/$1/* 2>&-); do (
			[ -f $script ] && . $script
		); done
	fi
}
