#!/bin/sh

mtk_wps_start() {
	iface0='ifname=ra0'
	iface0=`uci show wireless | grep ${iface0}`
	iface0=${iface0#*.}
	iface0=${iface0%%.*}

	iface1='ifname=rai0'
	iface1=`uci show wireless | grep ${iface1}`
	iface1=${iface1#*.}
	iface1=${iface1%%.*}

	wifi_enable_2g=`uci get wireless.${iface0}.disabled`
	wifi_enable_5g=`uci get wireless.${iface1}.disabled`

	if [ "$wifi_enable_2g" = "0" ]; then
		ra0_wps_PBC
	elif [ "$wifi_enable_5g" = "0" ]; then
		rai0_wps_PBC
	else
		echo "wifi not enable!" > /dev/console
	fi
}

ra0_wps_PBC() {
	iwpriv ra0 set WscConfMode=7
	iwpriv ra0 set WscMode=2
	iwpriv ra0 set WscGetConf=1
}

rai0_wps_PBC() {
	iwpriv rai0 set WscConfMode=7
	iwpriv rai0 set WscMode=2
	iwpriv rai0 set WscGetConf=1
}

case "$1" in
	start) mtk_wps_start;;
esac

