#!/bin/sh /etc/rc.common

. /usr/share/libubox/jshn.sh


CONFIG_PATH=/etc/config/bandwidth_config

index=0
wanname=''
table_id=200



#############    IP ROUTE Setting        ########################
# iter through ubus
for entry in `ubus list | grep wan | cut -d . -f 3`; do

    if [ "$entry" = "wan" ]; then
        wanname=wan0
        br_name=wan
    else
        wanname=wan${index}
        br_name=wan${index}
    fi


    #echo $wanname
    #echo $br_name
    #echo $table_id

    # cut nexthop
    nexthop=$(ubus call network.interface.${br_name} status | jsonfilter -e '@.route[*].nexthop' | grep -v '0.0.0.0')

    #nexthop=$(ubus call network.interface.${br_name} status | jsonfilter -e '@["route"][1].nexthop')

    # check rt_table
    rt_name=$(grep ${wanname} /etc/iproute2/rt_tables | grep -v _${wanname})
    if [ "$rt_name" == "" ]; then
        echo ${table_id} ${wanname} >>/etc/iproute2/rt_tables
    fi

    # this command is bug
    #grep -q  ${wanname}  /etc/iproute2/rt_tables || echo ${table_id} ${wanname} >>/etc/iproute2/rt_tables

    ip route replace default via ${nexthop} dev br-${br_name} table ${wanname}
    #echo "ip route replace default via ${nexthop} dev br-${br_name} table ${wanname}"

    index=$((index + 1));
    table_id=$((table_id + 1));
done
###############################################################
