#!/bin/sh

. /lib/functions.sh

echo "the button'${BUTTON}' change ${ACTION}" > /dev/console
if [ "${ACTION}" = "pressed" ]; then #repeater mode
	reboot
elif [ "${ACTION}" = "released" ]; then #router or ap mode
	reboot
fi
