#!/bin/sh

. /lib/functions.sh

echo "the button'${BUTTON}' change ${ACTION}" > /dev/console
if [ "${ACTION}" = "pressed" ]; then #ap mode
	reboot
elif [ "${ACTION}" = "released" ]; then # router or repeater
	reboot
fi
