#!/bin/sh

echo "change ${ACTION}" > /dev/console
if [ "${ACTION}" = "pressed" ]; then

echo $ACTION > ./tmp/sysinfo/button_state
./bin/button_light &

elif [ "${ACTION}" = "released" ]; then

echo $ACTION > ./tmp/sysinfo/button_state

. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"

board_name=$(cat /tmp/sysinfo/board_name)

if [ "$SEEN" -lt 1 ]
then
	kill -9 $(pidof button_light)
	case "$board_name" in
	cf-e500n | \
	cf-e510n | \
	cf-wr800n) 
		echo "WPS Start" > /dev/console
		wps start
	;;
	cf-wr752acv2 | \
	cf-wr753ac | \
	cf-wr755ac)
		echo "MTK WPS Start" > /dev/console
		mtk_wps start
	;;
	cf-wr754ac)
		echo "no something to do" > /dev/console
	;;
	*)
		echo "REBOOT" > /dev/console
		sync
		reboot
	;;
	esac


elif [ "$SEEN" -gt 5 ]
then
	echo "FACTORY RESET" > /dev/console
	jffs2reset -y && reboot &
fi
fi
