#!/bin/sh
. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"

board_name=$(cat /tmp/sysinfo/board_name)

if [ "$SEEN" -lt 1 ]
then
	kill -9 $(pidof button_light)
	case "$board_name" in

	cf-wr754ac)
		echo "MTK WPS Start" > /dev/console
		mtk_wps start
	;;

	esac
fi
